name: 🤒 Regression
description: This used to work, but a change in the service/tasks broke it. (Please make sure you know the last known working version)
title: "[REGRESSION]: "
labels: ["regression", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form if you'd like to report bug related to one of the 
        tasks. [List of the tasks](https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks)
  - type: checkboxes
    id: new-issue-checklist
    attributes:
      label: New issue checklist
      description: |
        Please make sure you've completed the following tasks before submitting your issue. Thanks!
      options:
        - label: I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)
        - label: I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
        - label: I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)
  - type: textarea
    id: what-happened
    attributes:
      label: Regression Description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A regression happened!"
    validations:
      required: true
  - type: input
    id: task-name
    attributes:
      label: Task name
  - type: input
    id: breaking-task-version
    attributes:
      label: Breaking task version
      placeholder: x.x.x
  - type: input
    id: working-task-version
    attributes:
      label: Last working task version
      placeholder: x.x.x
  - type: markdown
    attributes:
      value: |
        ## Environment 
  - type: dropdown
    id: environment-type
    attributes:
      label: Environment type (Please select at least one enviroment where you face this issue)
      options:
        - Self-Hosted
        - Microsoft Hosted
        - VMSS Pool
        - Container
      default: Microsoft Hosted
  - type: dropdown
    id: azure-devops-type
    attributes:
      label: Azure DevOps Server type
      options:
        - dev.azure.com (formerly visualstudio.com)
        - Azure DevOps Server (Please specify exact version in the textbox below)
    validations:
      required: true
  - type: input
    id: azure-devops-server-datails
    attributes:
      label: Azure DevOps Server Version (if applicable)
      placeholder: Azure DevOps Server 2019.1
  - type: input
    id: operation-system
    attributes:
      label: Operation system
      placeholder: Windows 11, Ubuntu 20.04...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Logs 
  - type: textarea
    id: task-logs
    attributes:
      label: Task log
      description: |
        Please copy and paste any relevant log output.
      render: shell
    validations:
      required: true
  - type: textarea
    id: error-logs
    attributes:
      label: Relevant log output
      description: |
        Insert error from the logs here for a quick overview
      render: shell
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting
